services:
  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt:2025.6.5@sha256:15091b35d0bfbd4bfec2c41ced5ef66fcb07bc5e8d0bf6a05fdf95aedcd89493
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /root/wireless-stack/rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - /root/wireless-stack/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt