services:
  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt@sha256:1abf2a998401869c34a7c1e7c7fe411bb9af2a866a005aacb25edd016b1e80a1
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /root/wireless-stack/rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - /root/wireless-stack/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt