services:
  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt:2.3.4@sha256:101b036a73f48e55ddfaf40762f83696a059db3dbaf00ebbd387e72a1c9eeb54
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /opt/rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - /opt/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt