---
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.5-nbxyz5@sha256:d0afc9da08c25f1a6f6b5442a741a9ab11057abc7fff498275d76adc13438866
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - netboot-config:/config # optional
      - netboot-assets:/assets # optional
    ports:
      - 3000:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
volumes:
  netboot-config:
  netboot-assets:
