services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.5.8@sha256:f534116c53d49b3120961c908a5fa24f28684806bf222ccd74add9e16b105aa4 # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: always
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - music-assistant-server:/data/
      - music:/media/music
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info

volumes:
  music-assistant-server:
  music:
    driver_opts:
      type: "nfs"
      o: "addr=tycho.corp,nolock,soft,ro"
      device: ":/mnt/Zpool/Media/Music"